include /home/renshujia/2023_work/cProgram/makeTemplate/env.make

# 基础变量
TARGET = libCJSON.so
# DST_DIR := $(BUILD_DIR)/$(notdir $(shell pwd))

# 编译选项
CFLAGS = \
	-fPIC

# 目录选项
IFLAGS = \
	-I. \

# 链接选项
LDFLAGS = \
	-shared



include /home/renshujia/2023_work/cProgram/makeTemplate/rules.make
