#本文件进行cJSON动态库的构造工作


include /home/renshujia/2023_work/cProgram/makeTemplate/env.make


# 基础变量
TARGET = SysOb

# 编译选项
CFLAGS = \

# 目录选项
IFLAGS = \
	-I. \
	-I../cJSON \

# 链接选项
LDFLAGS = \
	-L../cJSON \



include /home/renshujia/2023_work/cProgram/makeTemplate/rules.make
